### PR TITLE
escape backticks

### PR DESCRIPTION
**Pull request by git9527**
in case the field is already wrapped by backticks (`)

### CODE REVIEW

**Comment by ijgnd** [comment]
Thanks for your help. 

This commit breaks my very basic cards - I just put {{back}} on into my template and have something like nidd0123456789012 in the field back.

I guess you need your commit for fields in a js fuction in the front or back template of your card. My add-on should handle this use case, too. Maybe use both code versions with an if-else statement?

Your commit affects the [card_will_show](https://github.com/ankitects/anki/blob/f5abd3c6afdb876cb999feeceece5a285621aa01/qt/aqt/reviewer.py#L362) hook. The card_will_show hook has two arguments. The first is the munged/merged html of all relevant fields. I can't think of a simple way to identify the source field of some string. The other part that get's passed is the card object. By running card.note() you can get the underlying note. Then you have note.fields or note.tags. Maybe one special tag could be used to select which replacement code is used but then it's one decision for the whole card.

Maybe I should add new custom prefixes like jnidd/jcidd that apply your replacements?

**Comment by ijgnd** [comment]
note to self: I could also use note.note_type()/model(). That's my favorite.

**Comment by git9527** [comment]
Sorry, this PR did break the basic template, here is my use case

var originQuestion = \`{{question}}\`
// To avoid potential ' and " in question field, so I use `

when the merged html got replaced, it will become something like this:

var originQuestion = \`\<a href="javascript:pycmd(\`cidd1663850552495\`);">cidd1663850552495</a>\`

that will break the whole html

**Comment by ijgnd** [comment]
yes I understand your problem and I think the add-on should handle your use-case. But I wonder what's the best way to do this.

**Comment by ijgnd** [comment]
I just uploaded a new version. add your note type name to the config key "transform quoted for these notetypes". Let me know if it works.

**Comment by git9527** [comment]
Thanks, it works now

**Pull request closed without merging**
